# Workflow simple pour déployer des fichiers statiques vers le service GitHub Pages
# copié depuis le créateur d’actions GitHub

# Nom pour affichage de la tâche dans l’interface web
name: Déployer des fichiers statiques vers GitHub Pages

on:
  # Les branches pour lesquelles déclencher ce workflow
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab (autogénéré)
  workflow_dispatch:

# Permissions du GITHUB_TOKEN pour permettre le déploiement GitHub Pages (autogénéré)
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Une seule tâche, car nous ne faisons que déployer
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # étapes (auto-généré)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Préparer les pages
        uses: actions/configure-pages@v3
      - name: Téléverser les artéfacts
        uses: actions/upload-pages-artifact@v1
        with:
          # Téléverser tout le dépôt...
          # ... ou juste le répertoire `site`
          path: './site'
      - name: Déployer vers GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
