name: Site

on: push

jobs:
  servir_les_fichiers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Déploiement
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
