name: Site

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # create the slideshow as a regular index.html file
      - name: Fabriquer le HTML
        uses: docker://pandoc/core
        run: cd site && make 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
